title: Leon Dai
description: The occurences and random thoughs of a Waterloo ECE Student

baseurl: "/MyBlog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Leon Dai"
image: /thumbnail-jumbo.png
twitter:
  username:
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  app_id:  # cayman-blog
  #authors: lorepirri
#  admins:
